### ISSUE TITLE
Spec file 

### ISSUE THREAD

**Issue by asg017** [nalgeon/sqlpkg#1]
Hey Anton! First off, wanted to say that I love this project and I love having a single registry that I can point people to so they can find extensions. 

Secondly, I saw you mention a few times of having a "spec file" for sqlpkg. For my [`sqlite-package-manager`](https://github.com/asg017/sqlite-package-manager) project, I made a "spec file" format that sounds similar to what you want to make. At the very least, I want to share a few things I learned by making that spec file version (`spm.json`), which might help you making your version. But I also hope that your specfile would adopt enough features from `spm.json` so I can toss out my `spm.json` format and just use the `sqlpkg` spec format. 

## The current `spm.json` format

So in general, the `sqlite-package-manager` project has a few different features and goals from `sqlpg-cli`, but the `spm.json` file format seems very similar to what `sqlpkg`'s will be. 

For every SQLite extension project repo, a single `spm.json` file is uploaded to each Github release. For example, the `sqlite-vss` project has [this `v0.1.1-alpha.20` release](https://github.com/asg017/sqlite-vss/releases/tag/v0.1.1-alpha.20) which includes this `spm.json` file:

https://github.com/asg017/sqlite-vss/releases/download/v0.1.1-alpha.20/spm.json

The idea is that the `sqlite-package-manager` client will download this `spm.json` file, find which asset to download (based on the user's operating system / CPU arch), then download the right `.tar.gz` for the given platform. It has checksums for each `.tar.gz` asset that are checked before saving the individual extensions to the filesystem.

Currently the `spm.json` format is too specific to `sqlite-package-manager`, so take the format with a grain of salt. But there are a few things I like about it:

1. **There is one `spm.json` generated and uploaded in every Github release**. This is nice because there's checksums included for every release, and if I change the name / support a new platform in the future, I just uploaded a new release + `spm.json` file and handle it there. Also the `spm` CLI can just lookup to see if there's an `spm.json` file in the Github release for a specific version to see if the extension supports it. 
2. **The specfile can be automatically generated**. I have a Github action [upload-spm](https://github.com/asg017/upload-spm) that abstracts away the `spm.json` format and generation for extension authors. [Here's an example of how sqlite-vss](https://github.com/asg017/sqlite-vss/blob/main/.github/workflows/release.yaml#L180-L203) uses the step: the extension is pre-built in previous build steps, and all you have to do it point to a directory for each "platform" (`macos-x86_64`, `linux-x86_64`, etc.), and the `upload-spm` Action will handle uploading the `.tar.gz` files to Github Releases, and automatically generate + upload the `spm.json`  specfile.
3. **There are separate sections for loadable/static extensions.** Loadable extensions (`.dylib`/`.so`/`.dll`) are great for most cases, but you can also compile SQLite extensions as static archive files (`.a`), which can be used to statically compile extensions into C/C++/Rust/Go applications. I've only done a little bit with this [in sqlite-vss Go bindings](https://github.com/asg017/sqlite-vss/tree/main/examples/go), but it can be extremely helpful in the future to also support pre-compiled "static" extensions. 

## What I would add to a new specfile format

If I re-designed `spm.json`, I would have it like so:

```json
{
  "name": "sqlite-vss",
  "version": "0.1.1-alpha.20",
  "description": "",
  "authors" : ["Alex Garcia <alexsebastian.garcia@gmail.com>"],
  "license": "MIT",
  "repo": "https://github.com/asg017/sqlite-vss",
  "homepage": "https://github.com/asg017/sqlite-vss",
  "keywords": ["vector-search"],
  "edition": 0,
  "loadable": [
    {
      "os": "macos",
      "cpu": "x86_64",
      "url": "https://github.com/asg017/sqlite-vss/releases/download/v0.1.1-alpha.20/sqlite-vss-v0.1.1-alpha.20-loadable-macos-x86_64.tar.gz",
      "integrity": "sha256-e32633d3ec39b77e0463da785df69082c61baf649d0855bbc63c354082424cb5"
    },
    {
      "os": "macos",
      "cpu": "aarch64",
      "asset_name": "https://github.com/asg017/sqlite-vss/releases/download/v0.1.1-alpha.20/sqlite-vss-v0.1.1-alpha.20-loadable-macos-aarch64.tar.gz",
      "integrity": "sha256-f86754c25874908b224b37041df04518f13ccd40345c01a8b7e41fbc9355fa95"
    },
    {
      "os": "linux",
      "cpu": "x86_64",
      "asset_name": "https://github.com/asg017/sqlite-vss/releases/download/v0.1.1-alpha.20/sqlite-vss-v0.1.1-alpha.20-loadable-linux-x86_64.tar.gz",
      "integrity": "sha256-8491eccc2abf499bad31fb9c11b857b6c18b14c1ead040f99f1e298e7bc65257"
    }
  ],
  "static": [
    {
      "os": "macos",
      "cpu": "x86_64",
      "asset_name": "https://github.com/asg017/sqlite-vss/releases/download/v0.1.1-alpha.20/sqlite-vss-v0.1.1-alpha.20-static-macos-x86_64.tar.gz",
      "integrity": "sha256-d8049a78cdbb961e13f0b8be97809d7db456a673d68e5b82b1e9da08f5114a04"
    },
    {
      "os": "macos",
      "cpu": "aarch64",
      "asset_name": "https://github.com/asg017/sqlite-vss/releases/download/v0.1.1-alpha.20/sqlite-vss-v0.1.1-alpha.20-static-macos-aarch64.tar.gz",
      "integrity": "sha256-c9d6d61d1cd1425295271db90368e89378176f934709f246dcd8c71429bb0846"
    },
    {
      "os": "linux",
      "cpu": "x86_64",
      "asset_name": "https://github.com/asg017/sqlite-vss/releases/download/v0.1.1-alpha.20/sqlite-vss-v0.1.1-alpha.20-static-linux-x86_64.tar.gz",
      "integrity": "sha256-c22a209f1d12eda30a928c45457e222b2374c2130061b7627a262522112f7a76"
    }
  ]
}

```

- The name/version/description/authors/license/homepage/repo/keywords fields are just metadata, but could be nice to help build out your registry
- The "edition" key would be the format of the specfile, in case it needs updating in the future
- The `loadable`/`static` assets are split into different keys
- It would be very nice to standardize the OS/CPU architecture values. The `"macos"`/`"linux"`/`"windows"` part seems straightforward, but `"aarch64"` vs `"arm64"` and `"x86_64"` vs `"amd64"` vs `"x86"` can get confusing. In my opinion I like `"aarch64"` / `"x86_64"` but literally every programming language/package manager do not agree with each other

--- 

Let me know if there's anything I can clarify or help with! Happy to make a new Github Action that auto-generates a specfile if you're interested. I also have a version of `package.json`/`package-lock.json` - style project files in the form of [`spm.toml`](https://github.com/asg017/sqlite-package-manager/blob/main/examples/simple/spm.toml) and [`spm.lock`](https://github.com/asg017/sqlite-package-manager/blob/main/examples/simple/spm.lock) that I'd be more than happy to talk about, if you're interested.

**Comment by nalgeon** [comment]
Thank you, Alex! I am not sure why you are talking about the spec file as if it does not yet exist yet and I am only planning to design it. This `sqlpkg` registry and package manager are already built around spec files. This very repo contains package spec files. And [`sqlpkg-cli`](https://github.com/nalgeon/sqlpkg-cli) uses them to manage packages.

**Comment by asg017** [comment]
I did not notice that! Thanks for pointing it out.

Looking at the specfile, does this mean I'll have to send a PR to update a spec file on every new release?

**Comment by nalgeon** [comment]
You don't have to. The whole package registry thing is optional.

As an extension author, you can host your own `sqlpkg.json` (e.g. `https://github.com/asg017/sqlite-vss/sqlpkg.json`), and update it with other files when you [release a new version](https://github.com/asg017/sqlite-vss/commit/2c3d831248d7ec41411391e3162fe7c99075c33e). People can install your extension like this:

```
sqlpkg install github.com/asg017/sqlite-vss
```

And they'll always get the latest version.

The package registry will eventually sync with changes in your repository (although that part is not ready yet).

**Comment by asg017** [comment]
Are checksums of the individual extension files (or the `.tar.gz` itself) stored in the spec file at all? Or does the sqlpkg cli do anything with checksums?

**Comment by nalgeon** [comment]
Since that the checksums are only known after the build, I don't plan to store them in the spec file itself. Instead, they should be available for download along with the archives (like in [sqlite-vss](https://github.com/asg017/sqlite-vss/releases/tag/v0.1.1-alpha.20)). Then `sqlpkg` will check the downloaded archive against the corresponding checksum (not implemented yet, but planned).

**Comment by nalgeon** [comment]
`sqlpkg` release [0.1.0](https://github.com/nalgeon/sqlpkg-cli/releases/0.1.0) brings lockfile support, and release [0.2.0](https://github.com/nalgeon/sqlpkg-cli/releases/0.2.0) brings support for checksums. It also allows to specify the version as `latest`, without hardcoding a specific number.

I think that covers all the use cases you mentioned. Let me know if you have any further questions.
