### ISSUE TITLE
Advertise sqlpkg registry as part of individual package readme's

### ISSUE THREAD

**Issue by nyurik** [nalgeon/sqlpkg#12]
As part of the project description, e.g. [sqlite-compressions](https://github.com/nyurik/sqlite-compressions#readme), I would like to give a link to the sqlpkg registry.  This way you will grow ecosystem of packages, i.e. if a user discovers one, it will lead them to discover others.

To make this easier for developers, the sqlpkg should offer a few additional code and documentation things:
* Some recommended Markdown template text with links to include in the readmes.
* A way to link to a specific package in the registry
* An easy to copy/paste `badge` (shield) to include at the top of the readme, maybe even adding it to one of the well know badge generation systems like [this one](https://github.com/badges/shields)

**Comment by nalgeon** [comment]
You can give the link as follows:

```
https://sqlpkg.org/?q={id}
```

For example: <https://sqlpkg.org/?q=nyurik/compressions>

You can use any badge you like, for example:

```
https://img.shields.io/badge/sqlpkg-gray
https://img.shields.io/badge/sqlpkg-nyurik/compressions-blue
```

Probably with a link:

```html
<a href="https://sqlpkg.org/?q=nyurik/compressions">
    <img src="https://img.shields.io/badge/sqlpkg-nyurik/compressions-blue">
</a>
```

<a href="https://sqlpkg.org/?q=nyurik/compressions"><img src="https://img.shields.io/badge/sqlpkg-nyurik/compressions-blue"></a>

I don't have any recommended text to include in the readme, and frankly, I don't think I want to provide it.

**Comment by nalgeon** [comment]
[Sure](https://github.com/nalgeon/sqlpkg/blob/main/spec.md).
