### ISSUE TITLE
New sqlite extension

### ISSUE THREAD

**Issue by andreasbell** [nalgeon/sqlpkg#15]
Hi, I recently created an extension for deserializing procol buffers in sqlite.

You can find it [here](https://github.com/andreasbell/sqlite_protobuf) if you are intersted in adding it to sqlpkg.

**Comment by nalgeon** [comment]
Hi Andreas! I'm always happy to add an extension: https://sqlpkg.org/?q=andreasbell/protobuf

P.S. Despite the name, sqlite_protobuf-macos-aarch64.zip is compiled for x86_64 instead of arm64. Haven't tried others.

**Comment by andreasbell** [comment]
> Hi Andreas! I'm always happy to add an extension: https://sqlpkg.org/?q=andreasbell/protobuf
> 
> P.S. Despite the name, sqlite_protobuf-macos-aarch64.zip is compiled for x86_64 instead of arm64. Haven't tried others.

Thanks for the feedback. I see the names of the aarch64 and x64 names have been swapped in the build script, I will update the names in the release so that it is correct.
